version: '3.8'
name: ava_protocol_ethereum
services:
  ap-operator:
    env_file:
      - .env
    container_name: ap_operator_ethereum
    command:
    - operator
    - "--config=/app/config.yaml"
    ports:
      - ${PUBLIC_METRICS_PORT:-9190}:9090
      - ${PUBLIC_NODEAPI_PORT:-9191}:9010
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ${ECDSA_KEYSTORE_PATH}:/app/.operator-keys/operator.ecdsa.key.json:ro
      - ${BLS_KEYSTORE_PATH}:/app/.operator-keys/operator.bls.key.json:ro
      - ${DB_PATH}:/app/db:rw
    environment:
      OPERATOR_ECDSA_KEY_PASSWORD: ${ECDSA_KEY_PASSWORD}
      OPERATOR_BLS_KEY_PASSWORD: ${BLS_KEY_PASSWORD}
      PUBLIC_METRICS_PORT: ${PUBLIC_METRICS_PORT:-9190}
      PUBLIC_NODEAPI_PORT: ${PUBLIC_NODEAPI_PORT:-9191}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    image: ${AP_OPERATOR_IMAGE:-avaprotocol/ap-avs:latest}
    restart: unless-stopped
    networks:
      - ava

networks:
  ava:
    name: ava_ethereum
