{
 "title": "Ava Protocol Metrics",
 "description": "AP AVS Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "AvsName", "label": "AVS Name", "query": { "query": "label_values(avs_name)" } }
  ]
 },
 "panels": [
  { "title": "Avs Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hourly Uptime",
   "type": "stat",
   "description": "hourly total uptime in second of the oprator.",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(ap_uptime_milliseconds_total[1h]))/1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Performance Score",
   "type": "gauge",
   "description": "Performance score compare to other avs",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "eigen_performance_score", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ping Check Duration",
   "type": "gauge",
   "description": "The avg time the operator sync send ping check to aggregator in seconds",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ap_ping_duration_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Worker Loop",
   "type": "stat",
   "description": "Internal worker loop count of operator",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ap_num_worker_loop_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Ping",
   "type": "stat",
   "description": "The avg time the operator sync send ping check to aggregator in seconds",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ap_num_ping_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Data Syncing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Num Task Received",
   "type": "timeseries",
   "description": "amount of task received from server every 5mins",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(ap_num_tasks_received[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC Request Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eigen_rpc_request_total{avs_name=\"$AvsName\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  { "title": "Economics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Registered Stake",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(quorum_number) (eigen_registered_stakes{avs_name=\"$AvsName\"}) / 1000000000000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fees Earned",
   "type": "stat",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "eigen_fees_earned_total", "legendFormat": "__auto" }
   ]
  }
 ]
}