version: "3.8"
name: "watchtower"
services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: ap_autoupdater
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
    - ap_operator
    - "--cleanup"
    - "--interval"
    - "28800"
