global:
  scrape_interval: 1m
  evaluation_interval: 1m

scrape_configs:
  # scrpe AP operator metrics
  - job_name: 'operator-metrics'
    scrape_interval: 1m
    static_configs:
      - targets: ['ap_operator:9290']

  # Scrape the server metric itself
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
