global:
  scrape_interval: 1m
  evaluation_interval: 1m

# Set default port for scrapping
scrape_configs:
  - job_name: 'operator-metrics'
    scrape_interval: 1m
    static_configs:
      - targets: ['ap_operator:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
